### ISSUE TITLE
How to connect 2 supernodes for HA

### ISSUE THREAD

**Issue by dinopio** [ntop/n2n#44] opened 2018-09-25 12:28 UTC
According to this picture from the official [site](https://www.ntop.org/wp-content/uploads/2011/08/n2n_network.png) 2 supernodes can talk to each other (im hoping it can  used for High availability)

I have not found how this is done and if it can be done.
Can 1 edge connect to 2 supernodes ?

**Comment by lucaderi** [comment] 2018-09-29 10:35
We need to backport this feature in n2n v2

**Comment by lucaderi** [comment] 2018-09-29 10:38
This is a duplicate of #34

**Closed by lucaderi** 2018-09-29 10:38 UTC
Labels: enhancement
