### ISSUE TITLE
ERROR: Failed to decode common section in N2N_UDP

### ISSUE THREAD

**Issue by llfj** [ntop/n2n#641] opened 2021-02-21 12:31 UTC
edge v.2.9.0.r875.8589471
supernode v.2.9.0.r875.8589471 

Both windows（WIN10）and mipsel (LINUX) report errors 
Linux_x86 system does not report errors
All edge do not use -H and are the same version。

ERROR:
[OK] Edge Peer <<< ================ >>> Super Node
ERROR: Failed to decode common section in N2N_UDP
ERROR: Failed to decode common section in N2N_UDP
ERROR: Failed to decode common section in N2N_UDP
ERROR: Failed to decode common section in N2N_UDP

**Comment by Logan007** [comment] 2021-02-21 12:38
Thank you for reporting. May I ask if you have other edges, possibly connected to another supernode and using `-H`, in your local network?

I usually see this if I do my tests in a network and have some other edges (with another community and supernode) running. They receive encrypted REGISTERs from other edge nodes through the multicast port and can't decrypt those.

That definitely is one log message that needs to be downgraded from ERROR to DEBUG; probably during the [aspired](https://github.com/ntop/n2n/pull/627#issuecomment-782692449) log message review.

**Comment by llfj** [comment] 2021-02-21 12:41
Other EDGE (V2.7.0) are running on the network, and supernodes of different ports connected

**Comment by Logan007** [comment] 2021-02-21 12:44
Then those errors probably are caused by local multicast REGISTERs from the other edges. So, the message is nothing to worry about for now. We should downgrade from ERROR to DEBUG **or** make ignore this error if the provoking packet originates from the multicast socket.

**Comment by lucktu** [comment] 2021-02-26 12:56
> 
> 
> Then those errors probably are caused by local multicast REGISTERs from the other edges. So, the message is nothing to worry about for now. We should downgrade from ERROR to DEBUG **or** make ignore this error if the provoking packet originates from the multicast socket.

edge -a 10.128.128.111 -c abcd -k cdsa -l n2n.lucktu.com:10090 -p 22346 -t 45781 -ErA

Yes, I also encountered this error between windows 7(32) and Ubuntu (64) . edge_r874 and edge_r863. This error is also present in V2.8

In the same router, when do not show the above error, show that the supernode is not reachable, then can not be p2p, but the transfer by supernode (judging by ping) . In the Actual Ping Process (when p2p) , it will break halfway, but under V2, it will not break.

The good news is that v2.9 is now p2p under the same router, while v2 is not.

**Comment by Logan007** [comment] 2021-02-26 18:19
> In the same router, when do not show the above error, show that the supernode is not reachable, then can not be p2p, but the transfer by supernode (judging by ping) .

Thank you for testing and reporting! I truly beliebe that it is the multicast socket receiving (possibly encrypted or from another community) REGISTERs from other edges in the local network that just do not seem useful to the edge, hence the error message.

Again, this is not a real error. The message is misleading. I will change the error message and the level to DEBUG while reviewing the log messages.

> The good news is that v2.9 is now p2p under the same router, while v2 is not.

I am glad for you!

**Comment by tlsalex** [comment] 2021-02-27 14:28
I also see the same error message from the edge on my home PC tonight.
I also run edge on my server,  but it doesn't show me any error in last 3 days.
I still run N2N that was build on the commit of 6902189.
I feel strange ,why only my home edge got the error , and the server edge does not got that error message,these two edges should always communicate each other, as I tunnel my home traffic to the edge on server. Will it be an issue that hasn't been identified? Will it be some smart network devices (e.g firewalls) from ISP tried to detect my connection by sending some special package? 

```
27/Feb/2021 22:02:33 [edge_utils.c:1300] WARNING: Supernode not responding, now trying xx.xx.xx.xx:8080
27/Feb/2021 22:02:34 [edge_utils.c:2137] ERROR: Failed to decode common section in N2N_UDP
27/Feb/2021 22:02:39 [edge_utils.c:1300] WARNING: Supernode not responding, now trying xx.xx.xx.xx:8080
```

**Comment by Logan007** [comment] 2021-02-27 14:51
> I feel strange ,why only my home edge got the error , and the server edge does not got that error message

Do you have other edges running at your home network, maybe on the same or some other computer at home?

If yes, they will send REGISTER packets to the local multicast group, to all computers on the same local network. If those REGISTERs are encrypted (or maybe from another community, or maybe even a different n2n version, not sure about these two points yet) the message is shown.

> Will it be an issue that hasn't been identified?

If my assumption is correct, this is no real issue / error. It only is a misleading error message which will be fixed very soon.

**Closed as completed** 2021-02-27 15:44 UTC
Labels: question
