### ISSUE TITLE
Segmentation fault on Supernode

### ISSUE THREAD

**Issue by cholley** [ntop/n2n#593] opened 2021-01-18 15:04 UTC
I just downloaded the the latest dev code 1 hour ago,  and tested it. But it gives me "Segmentation fault" on supernode:
![image](https://user-images.githubusercontent.com/10412149/104931650-a70b9580-59e1-11eb-8184-ded4115f9145.png)
![image](https://user-images.githubusercontent.com/10412149/104932470-a1fb1600-59e2-11eb-8651-decea2be776d.png)

![image](https://user-images.githubusercontent.com/10412149/104931875-fb167a00-59e1-11eb-855e-bbe754637f90.png)
![image](https://user-images.githubusercontent.com/10412149/104932202-55afd600-59e2-11eb-880f-d84c5602e8c7.png)

What did I do?
Just run supernode, then run edge, after few seconds, it is crashed.

**Comment by Logan007** [comment] 2021-01-18 15:19
Thank you for reporting. I will have a look.

How many supernodes? How many edges?

Did it happen only once or over and over again in the same situation if you try again?

And also, did you rebuild all the edges and the supernodes?

**Comment by cholley** [comment] 2021-01-18 15:32
> Thank you for reporting. I will have a look.
> 
> How many supernodes? How many edges?
> 
> Did it happen only once or over and over again in the same situation if you try again?
> 
> And also, did you rebuild all the edges and the supernodes?

1 edge and  1 supernode. It is crashed when I started to test.
With the source code with RTT-based selection patch I download on the 5th, Jan. there is no such issue.

**Comment by Logan007** [comment] 2021-01-18 17:45
I am trying to re-produce and debug. Will report back what I find.

**Anyone else experiencing this, please report your parameters / scenario (as simple as possible) leading to the segfault.**

**Comment by Logan007** [comment] 2021-01-18 21:15
I tried the exact same data (my own ip addresses of course) and have not seen a segfault.

The screenshots you provided indicate two issues. I am not sure if those are responsible for the segfault you see, especially as it works over here with the exact same settings, but maybe it's worth a try:

- The path to the `community.list` file as provided in the `supernode.conf` file is different from the path from which you `cat`ed the `community.list` file ( +/-  `.../node/...`).
- The network notation in the `community.list` file is not as expected. The final digit should be 0 in a /24 network.

Those two points will lead the supernode to the assumption that no `community.list` file is provided. Even if the path were correct, it would ignore the entries with the deviating network notation.

Does it change anything if you correct those points?

Also, I see a lot of "seemingly encrypted header" messages on your supernode screenshot. This could be caused by using `-H` on some other edge, or maybe a federated supernode with a different `-F` setting, or just junk traffic.

Furthermore, did you upgrade the code to the same directory? You would have need to run `make clean` after upgrading the code then.

**Comment by cholley** [comment] 2021-01-19 02:01
Hi @Logan007 
I  noticed the community file path and the network notation issue. I will correct the settings  and try to do more test , maybe there is a pattern to  trigger it.

**Comment by Logan007** [comment] 2021-01-19 07:30
And please do not forget to run `make clean` before running `make` again…

**Comment by Logan007** [comment] 2021-01-29 12:58
Do you still observe the segfault? I think it might be time stamp related, I am on it. EDIT: _Oh, but that was on edge side, see #612_

May I ask what kind of platform (CPU, OS) you use for the supernodes?

**Comment by Logan007** [comment] 2021-02-19 09:10
Any news?

**Comment by Logan007** [comment] 2021-03-18 11:23
@cholley, can you re-produce this segmentation fault? Please let me know so we can better debug.

**If** you are able to re-produce, please configure `./configure CFLAGS="-fsanitize=address -g"`, `make clean` and `make` again. Then, please share the output that comes along with the seg fault. Thank you!

**Comment by Logan007** [comment] 2021-03-25 17:33
I found the following: 

A segmentation fault occurs after a while in supernode's main loop at the following HASH_ITER line (2087 of current `sn_utils.c`):

```
#ifdef N2N_HAVE_TCP
        // add the tcp connections' sockets
        HASH_ITER(hh, sss->tcp_connections, conn, tmp_conn) {
            //socket descriptor
            FD_SET(conn->socket_fd, &socket_mask);
            if(conn->socket_fd > max_sock)
                max_sock = conn->socket_fd;
        }
#endif
```

It says that it wanted to access some memory that had been freed before, referencing `purge_ peer_list()` of `n2n.c:482` meaning that a TCP connection got closed by purging.

However, I have not been able to see yet how the purge could impact the HASH_ITER as they happen at different places in the code (not interwoven). Is there anyone seeing a coding error?

_Meanwhile, I got another error, pointing to another part of the when accessing a conn-element. Maybe, the TCP conn list gets messed up at some point?_

_It seems related to the TCP implementation. Commenting `include/n2n.h`'s line 35 helps it... but disables TCP support._

**Closed as completed** 2021-03-26 15:00 UTC
Labels: bug

**Comment by Logan007** [comment] 2021-03-26 16:59
Running on #674 for a while now confirms much more stability, i.e. no issues even with very active TCP usage out here so far.
