### ISSUE TITLE
DHCP is not working/lack of documentation

### ISSUE THREAD

**Issue by pojntfx** [ntop/n2n#178] opened 2019-09-17 00:14 UTC
Currently, the documentation on how to use DHCP is lacking IMHO.

I've been trying to implement the following setup:

Node 1 (`supernode`, `edge` and `dnsmasq`):

```bash
root@node-1:~# supernode -l 1234 -v
17/Sep/2019 02:34:24 [sn.c:1009] WARNING: Running as root is discouraged
17/Sep/2019 02:34:24 [sn.c:1019] supernode is listening on UDP 1234 (main)
17/Sep/2019 02:34:24 [sn.c:1027] supernode is listening on UDP 5645 (management)
17/Sep/2019 02:34:24 [sn.c:1029] supernode started
```

```bash
root@node-1:~# edge -c hirschkopfnet -k hkn -r -a 192.168.0.1 -f -l 116.203.88.162:1234
17/Sep/2019 02:34:39 [edge_utils.c:1896] Adding supernode[0] = 116.203.88.162:1234
17/Sep/2019 02:34:39 [edge.c:673] Starting n2n edge 2.5.1 Sep 16 2019 21:15:34
17/Sep/2019 02:34:39 [edge.c:680] ip_mode='static'
17/Sep/2019 02:34:39 [tuntap_linux.c:43] Interface edge0 has MAC CA:86:14:C8:EC:FF
17/Sep/2019 02:34:39 [edge_utils.c:190] supernode 0 => 116.203.88.162:1234
17/Sep/2019 02:34:39 [edge.c:716] Interface up. Dropping privileges to uid=65534, gid=65534
17/Sep/2019 02:34:39 [edge.c:740] edge started
17/Sep/2019 02:34:39 [edge_utils.c:596] Successfully joined multicast group 224.0.0.68:1968
```

```bash
root@node-1:~# dnsmasq -p 0 -k --no-daemon --dhcp-range 192.168.0.20,192.168.0.50,72h --dhcp-option 1,255.255.255.0 --dhcp-option 28,192.168.11.255 --dhcp-option 3,192.168.11.250 --dhcp-option 6,192.168.11.251
dnsmasq: started, version 2.79 DNS disabled
dnsmasq: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
dnsmasq-dhcp: DHCP, IP range 192.168.0.20 -- 192.168.0.50, lease time 3d
```

Node 2 (`edge`):

```bash
root@node-2:~# edge -c hirschkopfnet -k hkn -r -a dhcp:0.0.0.0 -f -l 116.203.88.162:1234
17/Sep/2019 02:35:24 [edge_utils.c:1896] Adding supernode[0] = 116.203.88.162:1234
17/Sep/2019 02:35:24 [edge.c:673] Starting n2n edge 2.5.1 Sep 16 2019 21:15:34
17/Sep/2019 02:35:24 [edge.c:676] Dynamic IP address assignment enabled.
17/Sep/2019 02:35:24 [tuntap_linux.c:43] Interface edge0 has MAC E2:31:27:63:B6:AA
17/Sep/2019 02:35:24 [edge_utils.c:190] supernode 0 => 116.203.88.162:1234
17/Sep/2019 02:35:24 [edge.c:716] Interface up. Dropping privileges to uid=65534, gid=65534
17/Sep/2019 02:35:24 [edge.c:740] edge started
17/Sep/2019 02:35:24 [edge_utils.c:596] Successfully joined multicast group 224.0.0.68:1968
17/Sep/2019 02:35:24 [edge_utils.c:1753] Re-checking dynamic IP address.
```

No IP address gets assigned:

```bash
root@node-2:~# ip a
# (...)
13: edge0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1290 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether e2:31:27:63:b6:aa brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e031:27ff:fe63:b6aa/64 scope link 
       valid_lft forever preferred_lft forever
```

Logs on node 1 (`supernode`):

```bash
17/Sep/2019 02:34:39 [sn.c:645] New community: hirschkopfnet
17/Sep/2019 02:34:39 [sn.c:155] update_edge created   CA:86:14:C8:EC:FF ==> 116.203.88.162:40501
17/Sep/2019 02:35:24 [sn.c:155] update_edge created   E2:31:27:63:B6:AA ==> 116.203.50.42:41695
```

Logs on node 2 (`dnsmasq`):

```bash
# see above (no new logs)
```

I've tested `dnsmasq` on node 1, where it works just fine. If I assign a static IP to node 2 and then make a DHCP request, it works as well. The thing that is not working is the DHCP ip address assignment on node 2 with the `-r -a dhcp:0.0.0.0` option.

It would be awesome if there would be more docs on how to setup DHCP; if someone could help me with this specific setup here I'd be glad to write that of course.

**Comment by pojntfx** [comment] 2019-09-17 13:57
I just got it to work, not with DNSMasq though. On Fedora 30, the following works:

[GitLab Snippet](https://gitlab.com/snippets/1895685)

Sorry for any inconveniences!

**Comment by pojntfx** [comment] 2020-01-11 19:28
Reopening due to further problems; no DHCP server other than `dhcpd` from the ISC seems to work with `n2n`; I've tried `udhcpd`, `coredhcp` and a couple others. Has anyone found out why only this one specific DHCP server seems to work?

**Comment by pojntfx** [comment] 2020-01-11 19:35
I guess it might be this: https://serverfault.com/questions/86353/a-linux-dhcp-server-that-will-listen-on-an-non-broadcast-tap-interface

Maybe the other DHCP servers don't use raw sockets?

**Comment by emanuele-f** [comment] 2020-01-12 20:33
n2n uses tap (layer 2) interfaces, you should have no problem with dhcp. Make sure the dhcp server is started after the edge service and that the dhcp server is configured to listen on the n2n interface (or all the interface, see the "interface" setting in https://udhcp.busybox.net/udhcpd.conf for example).

**Comment by emanuele-f** [comment] 2020-03-28 21:37
Closing this assuming that the problem is now solved.

**Closed as completed by emanuele-f** 2020-03-28 21:37 UTC

**Comment by pretendb** [comment] 2020-07-24 06:57
hey guys, same problem as pojntfx, just can not get the dynamic ip from dhcp server
