### ISSUE TITLE
macos m1 warning WARNING: supernode not responding, now trying

### ISSUE THREAD

**Issue by bibitoo** [ntop/n2n#1055] opened 2022-10-30 03:08 UTC
Cant connect tu supernode .
sw_vers
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

I did not change any code, just git pull and cmake build, then run.
My prebuild version 2.9.0 can run well , but the new branch(3.1.1) not.

**Comment by Logan007** [comment] 2022-10-30 09:03
Did you also update the supernode to same version?

**Comment by bibitoo** [comment] 2022-10-31 14:40
yes，I also update the supernode . I also deploy the supernode at local network machine, set the n2n log level to debug mode, and I can't see supernode recieve package log. Maybe the edge could not send packets to supernode?

**Comment by bibitoo** [comment] 2022-10-31 15:00
I have been run codesign -s ~ edge, but nothing change.

**Comment by JimLee1996** [comment] 2022-12-20 12:05
same problem with bibitoo :-(

**Comment by Logan007** [comment] 2022-12-20 14:23
> Maybe the edge could not send packets to supernode?

Or, the supernode does not receive it due to some firewall settings? Any MacOS user?

**Comment by JimLee1996** [comment] 2022-12-20 14:26
Another test details:
When edge connecting supernode with -S2 (tcp mode), it works.
However when edge connecting supernode with -S1 or without -S option (udp mode), it fails.

**Comment by WtzLAS** [comment] 2023-01-15 04:21
> Another test details:
> When edge connecting supernode with -S2 (tcp mode), it works.
> However when edge connecting supernode with -S1 or without -S option (udp mode), it fails.

n2n fails to detect the sock address of the incoming UDP packets so it thinks that they come from unknown hosts

**Comment by JimLee1996** [comment] 2023-01-15 16:07
This issue is confirmed to be fixed on macOS Intel.

**Closed as completed** 2023-01-15 21:52 UTC
