### ISSUE TITLE
Can  anyone explain the logic about how does federation function work? 

### ISSUE THREAD

**Issue by cholley** [ntop/n2n#568] opened 2020-12-31 06:27 UTC
I just tested the federation function and it just not working at all. I use the latest dev code with a patch from issue #564 
When I killed one supernode, the other one is just ended up with "segmentation fault".
The test environment:
Supernode A (IP: 42.xxx.xxx.37):
`supernode -p 17654 -l 188.xxx.xxx.247:17654 -F omgd -a 192.168.234.0-192.168.234.0/24 -vvvv`
Supernode B (IP: 188.xxx.xxx.247):
`supernode -p 17654 -l 42.xxx.xxx.37:17654 -F omgd -a 192.168.234.0-192.168.234.0/24 -vvvv`
A and B form a federation with same community *omgd.

Edge C:
`edge -d edge0 -I tim001 -c n2n -k 12345 -l 42.xxx.xxx.37:17654 -f`
Edge D
`edge -d edge0 -I tim001 -c n2n -k 12345 -l 42.xxx.xxx.37:17654 -f`

Let's check the status of Supernode:
A:
![image](https://user-images.githubusercontent.com/10412149/103397265-8aaed280-4b72-11eb-9398-5361f9b72573.png)

B:
![image](https://user-images.githubusercontent.com/10412149/103397277-a1552980-4b72-11eb-8983-b85b6f43a342.png)

C:
![image](https://user-images.githubusercontent.com/10412149/103397710-753aa800-4b74-11eb-913b-744d4b7dd17c.png)

The 2nd supernode is not mine, I have no idea why it is in the list, so weird!

D:
no netcat, so did not check status.

on edge C, I ping the edge IP of D:
![image](https://user-images.githubusercontent.com/10412149/103397530-c5653a80-4b73-11eb-9133-b4a9b1af39a6.png)

Then I kill the supernode A, the connection between C and D is failed, and B is auto self-killed:
![image](https://user-images.githubusercontent.com/10412149/103397767-aca95480-4b74-11eb-873e-63d4ec0321aa.png)

If the federation works fine, the supernode B will take the responsibility to make sure C and D keep working, right?
That is how does the federation work?

**Comment by cholley** [comment] 2020-12-31 08:11
About the federation, I have some ideas maybe it can help to improve the feature.
* For Supernode:
All supernodes joint the same community will form a federation, and they are aware of each other. They can sync a list to show all supernode with IP:port to talk to each other, and the list should be the same on each supernode when you check it with netcat. 

But how to control the sync process? I think there should be a master supernode, and others will be slaves. When you form a federation, the first supernode without `-l IP:port` parameter will be the master, other supernodes join the federation with master IP, and they will be slaves in the list, so the master will get the full list and it will be responsible to sync the list to all slaves when a supernode joined and update every period of time, maybe every second, or set by a parameter.

If the Master is not reachable, then the slaves who detected the master is gone in the first second will take the position of Master, and it will notify all other slaves it is master now, and sync the latest list to them.

Meantime, all supernodes should also have a list to show all edges, the list will be synced as the same as the above supernode list. That means the supernodes should have 2 full lists of both supernodes and edges. This will help to identify all edges when some supernodes are down and no need to register one by one again because they already shared the authorized edge list.

* For Edge:
The edge can join any one of the supernode of federation and create the subnet, just do it as standalone mode. Only one `-l IP:port` parameter is needed, just make sure the IP:port is one of the supernode. After the edge joined the network, the supernode will sync the full supernode list to the edges, so all edges will have full supernode list, this will help to failover once the primary supernode is down. 

How to choose the failover supernode after primary supernode is down? It can be random, or sequentially. Just pickup any one of list, it will work, because every supernode knows all edges.

* Advanced feature about the traffic path
N2N is mainly focused on the p2p connection, so p2p will be the top priority for the traffic.
But it is might be not a good idea to choose p2p in some cases.
For example, i have 2 edges all over the world. 
edge A, B  and Supernode C are in different countries.
A--->B  260ms
A--->C   160ms
C--->B  60ms
A---->C ---->B 220ms
In this case, p2p for A and B is not that good, proxy via C will be better.
This happens in the real world, Some ISP provide do not have the direct mainline between countries or different providers, redirect the traffic will be better in that case.

So, how to choose the best path for traffic?
I have a logic based on delay:
If A has a list to show the delay between A to all supernodes, and it is listed by delay time, from low to high:
A---->sn1  140ms
A---- >sn2  170ms
A---->sn3  100ms
A----->B    260ms
and B has  the same list:
B---->sn1   60ms
B---- >sn2  70ms
B--->sn3   150ms
B---->A     260ms

Before A send a lot of traffic, it will ask B to send the list:
A: B, send me the list;
B: ok, here you are;
A: p2p is 260ms, not good, let's go through sn1, it will save 60ms.
B; ok, sn1 is good, let's do it.

Then, A will send traffic to sn1, and sn1 will redirect the traffic to B.
of course, This case is limited by supernode bandwidth, you have to think about it when you want to use this kind of feature.
might a switch option can help, turn it off will use p2p primarily, turn it on for smart traffic path.

hmmm, I said too much here, not sure it is reasonable or not, if something wrong, please let me know. thanks!

**Comment by Logan007** [comment] 2020-12-31 12:34
Okay, let's start with the more common part before getting to your specific scenario.

> They can sync a list to show all supernode with IP:port to talk to each other, and the list should be the same on each supernode when you check it with netcat.

Actually, the `netcat` on the management port shows the list of all reached supernodes so far, the entries you have seen under _*omgd_ community. A supernode just does not list itself. This internal data already is shared among the supernodes (they register to each other) and passed on to the edges with each repeatedly occurring edge registration.

> But how to control the sync process?

No need to further control the sync process, it is already there. Just provide another supernodes' IP address via `-l IP:port` to the **supernode**. You can provide as many as you want. Those additional supernodes provided via `-l …` will be exchanged between supernodes and also pushed to edges. The supernodes register to each other and forward their own knowledge about other supernodes with the answer to the registration. That way, the knowledge even of newly added supernodes is propagated throughout the whole federation. However, the supernodes need to be part of the same federation. There is a default federation, you can chose your own name if you wish to do so (`-F <federationName>`).

Dynamically enhancing a federation by a new supernode is as easy as starting up a new one with `-l …` option pointing to an existing one. Also, use the same federation name (`-F …`). If you provide a community list to the supernode (`-c …`), it should be same on all supernodes.

> I think there should be a master supernode, and others will be slaves.

They are all equal. Up to now, there is no need for a master or for slaves. As n2n might move even more towards p2p (edges and supernodes are all the same and especially equal), we should preferably concentrate on ways and algorithms that provide functionality among equal nodes.

> When you form a federation, the first supernode without -l IP:port parameter will be the master, …

Apart from not being able to see the need for a master-slave model, wouldn't that be a bit too complicated? And how to handle the case in which every supernode knows about additional supernodes through `-l`? In my opinion, there would be easier ways requiring less user intervention, e.g. just give the crown to the supernode with the highest MAC.

> Meantime, all supernodes should also have a list to show all edges, the list will be synced as the same as the above supernode list.

This happens during registration. Not only the supernodes register to each other and exchange information about other supernodes seen. Edges, too, receive information about alternative supernodes along with each and every answer (REGISTER_SUPER_ACK) to the repeating registration (REGISTER_SUPER).

Edges only need to know one of the supernodes at start-up (`-l …` option, too) and learn about the others as pushed from the supernodes. In fluctuating scenarios, you can provide more supernodes to edges at start-up to raise chances to initially find a still-alive supernode (simply add more `-l …` parameters). These supernodes provided to the edge through command line are **not** pushed into the federation. For security reasons, this is something only federated supernodes can do and remains reserved to them as only they know the correct federation name (default, if not chosen by `-F`).

> That means the supernodes should have 2 full lists of both supernodes and edges. 

Each edge should have a full supernode list after a while. The number of available entries submitted with each REGISTER_SUPER_ACK is limited, so it might take a few registration rounds to have the full picture at each edge.

The supernodes are meant to run on small computers, e.g. Raspberry Pi and routers. Therefore, we try to keep supernodes' resource requirements low. As of now, they only keep a list with full information of edges that actually are connected to them. We are thinking about keeping track of the other edges as well with MAC and IP only (not the full data-set) to allow for better routing through the federation (under development).

> How to choose the failover supernode after primary supernode is down?

It is the edges that chose the supernode they wish to connect to. Each edge pings the supernodes from time to time and receives a piece of information inside the answer. We did some trials using ping time (connect to the supernode with the lowest rtt) but decided to switch to a work-load based selection strategy. This is more in line with the idea of keeping workload low on (all) supernodes as it gets distributed more evenly.

So, basically, the ping serves two functions: See if a supernode is still alive and find out about its workload. The supernode reports its workload inside the answer to the ping.

An edge connects to the supernode with the lowest workload. It is re-considered with each re-registration. A _stickyness factor_ is implemented to avoid too much jumping between supernodes. Probably needless to say that edges only try to connect to supernodes that have been found alive. 

> So, how to choose the best path for traffic?

n2n's philosophy builds upon p2p being the best path. I myself [experienced](https://github.com/ntop/n2n/issues/291#issuecomment-665231045) that ping time might be higher on a p2p route than via a supernode. But there is more to a connection than its ping time. What does a fast round trip help if bandwidth is low?

To keep workload low on the supernodes, packet forwarding is the (sometimes unavoidable) exceptional case. I see no simple way to determine upfront how much traffic will be transmitted and to dynamically decide if a packet or a series of packets is better  sent via p2p or through the supernode. However, you have the `-S` option to intentionally disable p2p for certain edges, packets get forwarded through the supernode only then.

Your idea of comparing p2p rtt time to p**S**p (**S** == via **S**upernode) is interesting. Each edge would need to keep track of it. But remember that the route might change with each change of supernode, that is possibly with every re-registration. So, it would require to re-determine pSp rtt time for each edge and at each edge. That would produce a lot of extra traffic going through the supernode which we want to keep away as far as possible from unnecessary load.

> hmmm, I said too much here, …

We love discussions! Everyone's ideas, feedback  and contributions are very welcome. Exchanging thoughts and views is essential for further development.

**Comment by Logan007** [comment] 2020-12-31 12:58
> When I killed one supernode, the other one is just ended up with "segmentation fault".

This is definitely not supposed to happen!

While designing #564's code patch, I came across one oddity in the auto-IP feature. So, I suspect one detail of the current auto-IP feature implementation being responsible for the superfluous supernode entries. Furthermore, I guess that these superfluous supernode entries are responsible for segfaulting.

Could you please try to run your scenario with fixed IP addresses `-a 192.168.8.1` or `-a 192.168.8.2`, respectively, on edge's command line, and then let me know if 

- you still see additional ghost supernodes and
- you still see crashing supernode on ending the other one?

It will definitely help me to better find the cause for this issue. And just to be sure, could you run an additional round without `-F` then (will use default name then) and let me know the results?

Thank you!

> If the federation works fine, the supernode B will take the responsibility to make sure C and D keep working, right? That is how does the federation work?

Yes, that is the intention of the ping-and-re-register approach described in the earlier post. Obviously, there still is a bug which wants to be found and removed…

> The 2nd supernode is not mine, I have no idea why it is in the list, so weird!

The 3rd probably neither. Both do not look like real entries, their MAC addresses have too many zeroes. That will be part of the bug hunt.

**Comment by Logan007** [comment] 2021-01-02 11:53
I think I found the bug in the supernode's source code. It does not seem related to the auto-IP feature. Could you please try the following:

Edit the code of  `src/sn_utils.c` at line 1333. Originally, it should read

```C
            encode_REGISTER_SUPER_ACK(ackbuf, &encx, &cmn2, &ack, tmpbuf);
```

Please change the last parameter from `tmpbuf` to `payload_buf`:

```C
            encode_REGISTER_SUPER_ACK(ackbuf, &encx, &cmn2, &ack, payload_buf);
```

Re-compile and start the supernodes again. Please let me know if it works out for you.

**Comment by cholley** [comment] 2021-01-03 11:31
> I think I found the bug in the supernode's source code. It does not seem related to the auto-IP feature. Could you please try the following:
> 
> Edit the code of `src/sn_utils.c` at line 1333. Originally, it should read
> 
> ```c
>             encode_REGISTER_SUPER_ACK(ackbuf, &encx, &cmn2, &ack, tmpbuf);
> ```
> 
> Please change the last parameter `tmpbuf` to `payload_buf`:
> 
> ```c
>             encode_REGISTER_SUPER_ACK(ackbuf, &encx, &cmn2, &ack, payload_buf);
> ```
> 
> Re-compile and start the supernodes again. Please let me know if it works out for you.

Ok, I will patch the code and have a try, then update result later.

**Comment by cholley** [comment] 2021-01-04 04:23
> > I think I found the bug in the supernode's source code. It does not seem related to the auto-IP feature. Could you please try the following:
> > Edit the code of `src/sn_utils.c` at line 1333. Originally, it should read
> > ```c
> >             encode_REGISTER_SUPER_ACK(ackbuf, &encx, &cmn2, &ack, tmpbuf);
> > ```
> > 
> > 
> > Please change the last parameter `tmpbuf` to `payload_buf`:
> > ```c
> >             encode_REGISTER_SUPER_ACK(ackbuf, &encx, &cmn2, &ack, payload_buf);
> > ```
> > 
> > 
> > Re-compile and start the supernodes again. Please let me know if it works out for you.
> 
> Ok, I will patch the code and have a try, then update result later.

Hi @Logan007 

I applied the patch above, and the result is good, the federation is working.
But I have 2 questions about the working logic of the federation:
* 1. How did the edges choose the primary supernode?
I started supernode 1 and 2 to form a federation and run 2 edges with "-l supernode1 IP:port":
![image](https://user-images.githubusercontent.com/10412149/103500396-23509580-4e86-11eb-9735-845119507847.png)
check the pic above, you can see the -l option is related to 42.xx.xx.37, but the traffic is routed to 188.xx.xx.247.
This is not friendly, I can not see it by netcat, so I cap the data and find out the traffic is sending to 188.xx.xx.247.
Why is that?  Why the edges choose supernode 2 instead of 1?  how can i find which supernode is in service with netcat? or other easy way instead of capturing the packages?

* 2.  Is there a logic in the federation to choose the right supernode to decrease rtt time ？

When the edges choose supernode 2 for traffic, the rtt is 114ms, after i killed the supernode 2, the supernode 1 is active, and rtt is about 19.5ms. 
Check pic here:
![image](https://user-images.githubusercontent.com/10412149/103500868-67906580-4e87-11eb-8696-08fe921d2719.png)

Why does this happen? Is there a mechanism to check the supernodes and choose the right supernode to get shorter rtt time ?

For now, the federation is not so smart, how to make it smarter?

**Comment by Logan007** [comment] 2021-01-04 10:04
> I applied the patch above, and the result is good, the federation is working

Thank you for reporting back, that is great news!

> How did the edges choose the primary supernode?

The edges decide to which supernode to connect by workload they receive from the supernodes and which is calculated from the number of connected nodes, handled communities and a factor to respect extra-work due to header encryption (if enabled). The current supernode gets a bonus by applying a dynamic stickyness factor. The edges switch to the supernode with the reportedly lowest work**l**oa**d** (lowest `ld` value in edge's `netcat` output on management port  where `-1` means _offline_, i.e. no answer to ping).

> check the pic above, you can see the -l option is related to 42.xx.xx.37, but the traffic is routed to 188.xx.xx.247.

The list is sorted by workload and the edge usually is connected to the supernode on top of that list (+/- a few seconds because ping, sorting and re-registration do not happen at the same time). You can additionally verify by checking the supernode's management port output with `netcat` showing the edges connected to it. The remaining direct traffic between the edge and other (non-connected) supernodes should consist of some ping packets only. Please provide more details if you find something different.

However, the p**S**p traffic that passes through the supernode gets forwarded by the supernode to all the other supernodes if the target is not connected to the same supernode (one additional routing optimization to reduce the federation broadcast traffic is still work in progress). This is the regular behaviour for packets aiming at other edges (connected to the other supernode) as well as for broadcast/multicast traffic that makes it to the supernode.

> Is there a logic in the federation to choose the right supernode to decrease rtt time

> Is there a mechanism to check the supernodes and choose the right supernode to get shorter rtt time ?

No, not any more.

> Why does this happen?

As explained above, we primarily target balancing supernode's workload (not rtt) and have put some effort in this feature's realization. On the other hand, I understand your needs very well. Sometime or other, I might provide an optional patch to `src/sn_selection.c` for an rtt based selection scheme here of which I am doubtful whether it makes it into the official code.

> For now, the federation is not so smart, …

Please bear in mind that from the n2n perspective, p**S**p is considered the exceptional case of a packet's path.

> … how to make it smarter?

A colleague works on reducing federation broadcasts between supernodes.

Apart from rtt-based selection strategy, what do you suggest?

**Comment by Logan007** [comment] 2021-01-04 14:54
I did a real quick adoption of a pure-rtt-based sn selection scheme, please find attached a [patch](https://github.com/ntop/n2n/files/5765265/patch.txt). Hope it helps, let me know.

**Comment by cholley** [comment] 2021-01-04 15:28
> > I applied the patch above, and the result is good, the federation is working
> 
> Thank you for reporting back, that is great news!
> 
> > How did the edges choose the primary supernode?
> 
> The edges decide to which supernode to connect by workload they receive from the supernodes and which is calculated from the number of connected nodes, handled communities and a factor to respect extra-work due to header encryption (if enabled). The current supernode gets a bonus by applying a dynamic stickyness factor. The edges switch to the supernode with the reportedly lowest work**l**oa**d** (lowest `ld` value in edge's `netcat` output on management port where `-1` means _offline_, i.e. no answer to ping).

**During my test, I opened 2 windows to run the 2 supernode, both were online all the time until i killed one of them for testing the failover. So it is so weird to be showed off line with "ld = -1", maybe there is something wrong with the indicator of status**

> > check the pic above, you can see the -l option is related to 42.xx.xx.37, but the traffic is routed to 188.xx.xx.247.
> 
> The list is sorted by workload and the edge usually is connected to the supernode on top of that list (+/- a few seconds because ping, sorting and re-registration do not happen at the same time). You can additionally verify by checking the supernode's management port output with `netcat` showing the edges connected to it. The remaining direct traffic between the edge and other (non-connected) supernodes should consist of some ping packets only. Please provide more details if you find something different.
> 
> However, the p**S**p traffic that passes through the supernode gets forwarded by the supernode to all the other supernodes if the target is not connected to the same supernode (one additional routing optimization to reduce the federation broadcast traffic is still work in progress). This is the regular behaviour for packets aiming at other edges (connected to the other supernode) as well as for broadcast/multicast traffic that makes it to the supernode.
> 
**During pSp process, redirecting the packets to all supernodes might be not a good idea, it will take up lots of bandwidth and it seems not to be so necessary. If the edges can choose a proper supernode and notify other edge to use same supernode before sending traffic, it might be better for load balance, all supernodes will be not so busy.**

> > Is there a logic in the federation to choose the right supernode to decrease rtt time
> 
> > Is there a mechanism to check the supernodes and choose the right supernode to get shorter rtt time ?
> 
> No, not any more.
> 
> > Why does this happen?
> 
> As explained above, we primarily target balancing supernode's workload (not rtt) and have put some effort in this feature's realization. On the other hand, I understand your needs very well. Sometime or other, I might provide an optional patch to `src/sn_selection.c` for an rtt based selection scheme here of which I am doubtful whether it makes it into the official code.
>
> > For now, the federation is not so smart, …
> 
> Please bear in mind that from the n2n perspective, p**S**p is considered the exceptional case of a packet's path.
> 
> > … how to make it smarter?
> 
> A colleague works on reducing federation broadcasts between supernodes.
> 
> Apart from rtt-based selection strategy, what do you suggest?

**About the status of edges and supernodes, is there any more clear way to check the traffic path?
On edge, how to check which supernode is be using and the realtime data speed/bandwidth?
On supernode, how many supernode is be using and what is the realtime traffic speed/bandwidth?**

**Comment by cholley** [comment] 2021-01-04 15:30
> I did a real quick adoption of a pure-rtt-based sn selection scheme, please find attached a [patch](https://github.com/ntop/n2n/files/5765265/patch.txt). Hope it helps, let me know.

I will have a try and update the result asap. Thanks for your best effort!

**Comment by Logan007** [comment] 2021-01-04 17:05
> During my test, I opened 2 windows to run the 2 supernode, both were online all the time until i killed one of them for testing the failover. So it is so weird to be showed off line with "ld = -1", maybe there is something wrong with the indicator of status

`-1` is shown if no answer to a ping has been received (yet). There can be several reasons. Maybe the answer got lost? The `last_seen` values (72 or 102 seconds ago) are somewhat high and indicate that some answers must have been missing. A ping is repeated roughly every 30 seconds or so.

> During pSp process, redirecting the packets to **all** supernodes might be not a good idea, it will take up lots of bandwidth and it seems not to be so necessary. 

The federation is a freshly added feature which for now works the way it works. Narrowing this routing functionality is exactly what a colleague is working on. It will distribute packets to the one target supernode only. But again, as p**S**p is only the fall-back option in case p**2**p fails, we probably do not focus on even more sophisticated routing algorithms for packet forwarding between supernodes too soon.

> If the edges can choose a proper supernode and notify other edge to use same supernode before sending traffic, it might be better for load balance, all supernodes will be not so busy.

This sounds like an interesting supernode selection strategy, far more advanced than based on round trip time. It would require to analyse network traffic flows. I wish somebody could implement it.

> About the status of edges and supernodes, is there any more clear way to check the traffic path?

Management port output is all we have for now. The status contains pretty much all the data available at supernode and edge. If an edge appears under `supernode_forward`, packets will be forwarded (usually, to the supernode on top of the supernode list, see our discussion above). If they appear in the `peer_to_peer` category, they communitcate directly.

Soon, with the routing of forwarded packets, there will be information available on the supernode to what other supernode one other edge is connected. But I have no idea if it is worth outputting it. I would not recommend to push that information to the edges to keep the overall footprint low. Especially with a view to the fact that information might change all the time. n2n is supposed to run on small computing devices such as routers, too.

> On edge, how to check which supernode is be using and the realtime data speed/bandwidth?

Again, that should be the supernode on top of the list of supernodes, on the first line (+/- a few seconds after the ping).

Speed and bandwidth of the data link are not measured by n2n. You would need to use other common tools such as iperf or so.

You can check your computer's abilities for crypto and compression by running the `tools/n2n-benchmark` utility (not available on Windows, I guess). See our [Building](https://github.com/Logan007/n2n/blob/dev/doc/Building.md) documentation in the `/doc` folder for details about accelerative compiler options.

> On supernode, how many supernode is be using and what is the realtime traffic speed/bandwidth?

You can count the number of connected edges for each community. Those listed under the federation community will give you the number of other supernodes.

Speed and bandwidth of the data link are not measured by n2n. You would need to use other common tools such as iperf or so.

**Comment by cholley** [comment] 2021-01-05 04:31
> > I did a real quick adoption of a pure-rtt-based sn selection scheme, please find attached a [patch](https://github.com/ntop/n2n/files/5765265/patch.txt). Hope it helps, let me know.
> 
> I will have a try and update the result asap. Thanks for your best effort!

**I have tested this patch and it is working like a charm! The edges can choose the supernode based on the rtt time during the traffic transmitting.**
![image](https://user-images.githubusercontent.com/10412149/103605580-3bd8b280-4f4f-11eb-8926-77ab934ff695.png)
![image](https://user-images.githubusercontent.com/10412149/103605661-76dae600-4f4f-11eb-8a4f-15afc623b2d1.png)

**i also tested multiple edges with multiple supernodes, they are working good with federation logic.**

I think this pure-rtt-based sn selection scheme is good enough for my application scenario and the federation is working good with multiple supernodes. 

The only issue is that the down time is a little long, if I kill the supernode which is in service for the edge, it will take  about 22s for the edge to choose another supernode to keep the connection alive, and it will take about  58s to choose another supernode with shorter rtt time. So may i know is there any parameters to lower the interval time of switching supernodes?

**Comment by Logan007** [comment] 2021-01-05 10:31
> I have tested this patch and it is working like a charm!

I am glad to hear.

> The only issue is that …

@cholley, please remember that you use n2n on its fallback-functionality only and therefore on the limits of its primary aims. It is still targeting p2p.

> … the down time is a little long

In a p2p scenario, the shortfall of a supernode does not need to be compensated so fast because the edges are still able to communicate with each other (p2p) while the loss of a supernode is being detected and the edge is re-registering.

> So may i know is there any parameters to lower the interval time of switching supernodes?

Indeed, there are opportunities to tune some values to your needs.
_____
:warning: **WARNING**

**YOU ARE LEAVING THE SAFE ZONE NOW!**

**THE `INCLUDE/N2N_DEFINES.H` FILE PROVIDES SOME VALUES THAT DETERMINE N2N'S BEHAVIOR. THOSE VALUES ARE WELL-BALANCED AND CHANGING THEM MAY SHOW UNWANTED SIDE-EFFECTS SUCH AS HIGHER NETWORK TRAFFIC, HIGHER CPU USAGE OR EVEN RENDERING THE SOFTWARE UN-STABLE OR UN-USABLE.**
_____

`SOCKET_TIMEOUT_INTERVAL_SECS` on line 45 could be lowered, **not lower than `1`**. Background tasks (purging, pinging) will be started more promptly then in times of low traffic. It will result in higher CPU load.

You could try to lower the time an edge waits between the pings. Then, pings happen more often and a supernode outage is detected earlier: `SWEEP_TIME` on line 49 could be lowered, **do not set it below `3`**. It will increase network traffic as every edge pings every supernode more often then.

Also, you could lower `REGISTER_SUPER_INTERVAL_DFL` value at line 46. **Do not go below `1`**, you should even stay well above it. The lower the value, the faster a supernode will re-register. But, it does it all the time. So, the lower the value, the higher the total idle network traffic, also between the edges.

Finally, the `N2N_EDGE_SUP_ATTEMPTS` could be lowered, **not below `1`**. This is the number an edge retries to (re-)register to a supernode before switching to another one.

Let us know what you find!

**Comment by cholley** [comment] 2021-01-08 07:12
> > I have tested this patch and it is working like a charm!
> 
> I am glad to hear.
> 
> > The only issue is that …
> 
> @cholley, please remember that you use n2n on its fallback-functionality only and therefore on the limits of its primary aims. It is still targeting p2p.
> 
> > … the down time is a little long
> 
> In a p2p scenario, the shortfall of a supernode does not need to be compensated so fast because the edges are still able to communicate with each other (p2p) while the loss of a supernode is being detected and the edge is re-registering.
> 
> > So may i know is there any parameters to lower the interval time of switching supernodes?
> 
> Indeed, there are opportunities to tune some values to your needs.
> 
> ⚠️ **WARNING**
> 
> **YOU ARE LEAVING THE SAFE ZONE NOW!**
> 
> **THE `INCLUDE/N2N_DEFINES.H` FILE PROVIDES SOME VALUES THAT DETERMINE N2N'S BEHAVIOR. THOSE VALUES ARE WELL-BALANCED AND CHANGING THEM MAY SHOW UNWANTED SIDE-EFFECTS SUCH AS HIGHER NETWORK TRAFFIC, HIGHER CPU USAGE OR EVEN RENDERING THE SOFTWARE UN-STABLE OR UN-USABLE.**
> 
> `SOCKET_TIMEOUT_INTERVAL_SECS` on line 45 could be lowered, **not lower than `1`**. Background tasks (purging, pinging) will be started more promptly then in times of low traffic. It will result in higher CPU load.
> 
> You could try to lower the time an edge waits between the pings. Then, pings happen more often and a supernode outage is detected earlier: `SWEEP_TIME` on line 49 could be lowered, **do not set it below `3`**. It will increase network traffic as every edge pings every supernode more often then.
> 
> Also, you could lower `REGISTER_SUPER_INTERVAL_DFL` value at line 46. **Do not go below `1`**, you should even stay well above it. The lower the value, the faster a supernode will re-register. But, it does it all the time. So, the lower the value, the higher the total idle network traffic, also between the edges.
> 
> Finally, the `N2N_EDGE_SUP_ATTEMPTS` could be lowered, **not below `1`**. This is the number an edge retries to (re-)register to a supernode before switching to another one.
> 
> Let us know what you find!

Hi @Logan007 

I only change the  `N2N_EDGE_SUP_ATTEMPTS ` to 1, which leads  the supernode switch interval changed from 60 seconds to 20 seconds:
![image](https://user-images.githubusercontent.com/10412149/103985177-7185d180-51c3-11eb-9858-fc09dbeb102f.png)

It is enough for me. Thanks a lot for your help!
btw, will you merge the changes about the supernode selection based on rtt time to the trunk source?

**Comment by cholley** [comment] 2021-01-08 07:19
I have a question about the community limitation function related to federation:
I use a community.list to limit the edges to access specific communities. Should I must keep the community.list the same in each supernodes which formed the federation?

If I use different community in different supernodes, how does the federation handle the communities?
eg:
SN1: home
SN2: office
SN3: god
Will the SN1 only accept edges with home, or it can allow all of them (home, office, god)?

**Comment by Logan007** [comment] 2021-01-08 16:57
> will you merge the changes about the supernode selection based on rtt time to the trunk source?

Focusing on load balancing for now as explained earlier in this discussion, I am not aware of changing plans. Even though we have chosen a modular approach to implement supernode selection strategy (nearly everything can be found in only the one `sn_selection.c` file) which allows for easily replacing it, it seems more a compile-time decision because data-types / packet-format depend on the decision for a selection strategy (run-time based would involve more complex code). So, even a command-line based selection (which would bring yet another command line parameter...) probably is out of reach.

One thing I am pondering is a compile-time selection which could be activated by configuring some macro definition, e.g. `-DRTT_BASED_SN_SELECTION` or so. But I am not sure yet.

> Should I must keep the community.list the same in each supernodes which formed the federation?

They do not necessarily have to be identical. But, if you want to let edges of the exact same listed communities use all your supernodes: yes.

> If I use different community in different supernodes, how does the federation handle the communities?

Each supernode allows only edges from its locally listed communities. At the same time, the edges get to know all supernodes of the federation. So, they will try to ping them all.

The supernode only answers to pings and registration attempts from an edge of a valid community. Therefore, the supernodes should not answer to an edge of an unlisted community (this does not apply if no `-c …` is provided to supernodes). The edge will mark it as unresponsive (load = -1) and will not try to register with it unless there is no other supernode alive. But even then, that supernode will not answer the registration because it does not know the community.

> Will the SN1 only accept edges with home, or it can allow all of them (home, office, god)?

It should accept only connections from _home_ community's edges then. But it still is visible to edges from the other communitites (which can not connect to it unless allowed by SN1's `-c ...` configuration).

**Comment by cholley** [comment] 2021-01-09 02:34
> > will you merge the changes about the supernode selection based on rtt time to the trunk source?
> 
> Focusing on load balancing for now as explained earlier in this discussion, I am not aware of changing plans. Even though we have chosen a modular approach to implement supernode selection strategy (nearly everything can be found in only the one `sn_selection.c` file) which allows for easily replacing it, it seems more a compile-time decision because data-types / packet-format depend on the decision for a selection strategy (run-time based would involve more complex code). So, even a command-line based selection (which would bring yet another command line parameter...) probably is out of reach.
> 
> One thing I am pondering is a compile-time selection which could be activated by configuring some macro definition, e.g. `-DRTT_BASED_SN_SELECTION` or so. But I am not sure yet.
> 
> > Should I must keep the community.list the same in each supernodes which formed the federation?
> 
> They do not necessarily have to be identical. But, if you want to let edges of the exact same listed communities use all your supernodes: yes.
> 
> > If I use different community in different supernodes, how does the federation handle the communities?
> 
> Each supernode allows only edges from its locally listed communities. At the same time, the edges get to know all supernodes of the federation. So, they will try to ping them all.
> 
> The supernode only answers to pings and registration attempts from an edge of a valid community. Therefore, the supernodes should not answer to an edge of an unlisted community (this does not apply if no `-c …` is provided to supernodes). The edge will mark it as unresponsive (load = -1) and will not try to register with it unless there is no other supernode alive. But even then, that supernode will not answer the registration because it does not know the community.
> 
> > Will the SN1 only accept edges with home, or it can allow all of them (home, office, god)?
> 
> It should accept only connections from _home_ community's edges then. But it still is visible to edges from the other communitites (which can not connect to it unless allowed by SN1's `-c ...` configuration).

Thank you!

**Comment by Logan007** [comment] 2021-01-09 10:14
You are most welcome!

**Closed as completed by Logan007** 2021-01-09 10:14 UTC
Labels: question

**Comment by Logan007** [comment] 2021-01-12 11:48
> > will you merge the changes about the supernode selection based on rtt time to the trunk source?

> One thing I am pondering is a compile-time selection which could be activated by configuring some macro definition, e.g. -DRTT_BASED_SN_SELECTION or so. But I am not sure yet.

#580
