### ISSUE TITLE
V2.9's domain name recognition is weaker

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#657] opened 2021-03-05 09:39 UTC
Edge_v2.9's domain name recognition is weaker, and V1 + V2 works equally well, while V2.9 doesn't (when edge and supernode are running on the same machine).

 WARNING: Supernode not responding, now trying ... ...

**Comment by Logan007** [comment] 2021-03-05 10:09
I am not sure if I correctly understand the issue. Do you think that this WARNING is caused by the name resolution?

As of current dev, the name resolution happens on each and every re-register.  #645 (not merged yet) changes it to being performed in the background and only once in a while.

The WARNING is issued when connection retries are exhausted and the next supernode will be tried -- if it is the only one, the same one gets retried, of course.

There can be several reasons why the retry counter might have been down to 0. It does not necessarily mean that the domain name resolution failed. By the way, if you use TCP, the retries are set to 1 only because TCP is intrinsically considered more reliable. For UDP, it is 3 attempts.

One more reason might be that edges do not purge their knowledge about supernodes to increase resilience. So, the edges will remember even supernodes not seen for a long time just in case they show up again. In test scenarios with often restarted supernodes, this might fill up edges' list. Usually, those should not be preferred for connection because they do not answer the PING any more and find themselves at the bottom of the list. You could check by taking a look at edge's management port output.

When going through the log messages, I will see if we can display a connection message after such a supernode re-connect.

Could you provide more details to get a better understanding of what exactly is happening in your scenario? Do you use named supernodes or raw IP addresses on `-l` command line? Do you use several supernodes or just one? Any special observations on management port output when this happens? Thank you!

**Comment by lucktu** [comment] 2021-03-05 13:12
Well, you're right.

My router is a padavan, and the edge inside uses the native supernode (v1/v2/v2s/V2.9) .

 If I change the domain name to Wan IP, the same warning will appear (here it is). Maybe it has something to do with the local firewall, v1, v2, v2s (MEYERD's V2) all work, but V2.9 doesn't. 

05/Mar/2021 21:04:10 [edge_utils.c:1156] WARNING: Supernode not responding, now trying 171.221.159.146:10090
05/Mar/2021 21:04:10 [edge_utils.c:2562] Binding to local port 20090

**Comment by Logan007** [comment] 2021-03-05 13:21
The immediately following "Binding to local port" message seems to indicate a directly appearing re-connection. I agree that it is not obvious. I will shape the log messages accordingly.

I still do not understand if it just the mesaage or if you experience a real and enduring loss of connection? How often does the message appear?

**Comment by lucktu** [comment] 2021-03-05 13:46
It's a real experiment.
It's never ping. 
Error message every 12 seconds.

**Comment by Logan007** [comment] 2021-03-05 15:22
I do not think that it is your firewall. I have just tried some local constellations and found one which shows similar symptoms. I will have a closer look and report back.

**Comment by Logan007** [comment] 2021-03-05 19:01
The situation I experienced  was caused by having two different network interfaces on the supernode which were resolved under the same local hostname... After fixing that (just assign a different names for LAN and WIFI-bound IP addresses on the router's web interface), I have not seen any issue.

Let me add that the function for name resolution still is the same `supernode2sock()`.

**Comment by lucktu** [comment] 2021-03-06 00:46
The same test did not show this problem on ubuntu 16.04.6

Edge_v2.9 and supernode_v2.9 run ubuntu, edge_v2.9 to supernode_v2.9, all clear.

Edge_v2.9 and supernode_v2.9 run padavan, edge_v2.9 doesn't connect to supernode_v2.9.

( edge3 -d e3 -a 172.5.5.55 -c abc -k cba -l n2n.lucktu.com:10090 -p 24589 -t 36789 -ErA )

I think it may still be the firewall problem, if there is no conclusive evidence, I suggest that appropriate to put aside, put their energy elsewhere.

Thank you very much for your high attention and dedicated spirit!

**Comment by Logan007** [comment] 2021-03-06 10:26
> The same test did not show this problem on ubuntu 16.04.6

This is indeed strange...

**Closed as completed** 2021-03-07 07:32 UTC
